vich_uploader:
    db_driver: orm

    mappings:
       cars:
           uri_prefix: /uploads/images/cars
           upload_destination: '%kernel.project_dir%/public/uploads/images/cars'
           namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
           
    
